const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('./src/models/Product');

dotenv.config();

const products = [
  // ============================
  // CAMISETAS (10)
  // ============================
  {
    nombre: 'Camiseta Nike Dry-Fit',
    descripcion: 'Camiseta deportiva de poliéster con tecnología Dry-Fit para máxima transpiración.',
    precio: 34.99,
    stock: 45,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500',
    marca: 'Nike',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Blanco', 'Azul'],
  },
  {
    nombre: 'Camiseta Adidas Originals',
    descripcion: 'Camiseta clásica con logo de Adidas, algodón 100% para uso diario.',
    precio: 29.99,
    stock: 50,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
    marca: 'Adidas',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Blanco', 'Rojo'],
  },
  {
    nombre: 'Camiseta Puma Essentials',
    descripcion: 'Camiseta básica de algodón con cuello redondo y ajuste regular.',
    precio: 24.99,
    stock: 60,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=500',
    marca: 'Puma',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Gris', 'Azul', 'Verde'],
  },
  {
    nombre: 'Camiseta Zara Básica',
    descripcion: 'Camiseta de manga corta con cuello redondo, tejido suave de algodón.',
    precio: 19.99,
    stock: 70,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500',
    marca: 'Zara',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Blanco', 'Negro', 'Beige'],
  },
  {
    nombre: 'Camiseta H&M Printed',
    descripcion: 'Camiseta con estampado gráfico, 100% algodón, estilo casual.',
    precio: 17.99,
    stock: 55,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=500',
    marca: 'H&M',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Blanco', 'Amarillo', 'Rosa'],
  },
  {
    nombre: 'Camiseta Under Armour',
    descripcion: 'Camiseta de compresión con tecnología HeatGear para deportes de alto rendimiento.',
    precio: 39.99,
    stock: 30,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1586363104863-3b5c2a769379?w=500',
    marca: 'Under Armour',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Gris', 'Rojo'],
  },
  {
    nombre: 'Camiseta New Balance',
    descripcion: 'Camiseta deportiva ligera con protección UV y costuras planas.',
    precio: 32.99,
    stock: 35,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1556906781-9a4129617d5b?w=500',
    marca: 'New Balance',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Azul', 'Negro', 'Naranja'],
  },
  {
    nombre: 'Camiseta Ralph Lauren',
    descripcion: 'Camiseta polo clásica con cuello y botones, tejido de algodón pima.',
    precio: 49.99,
    stock: 25,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1586363104863-3b5c2a769379?w=500',
    marca: 'Ralph Lauren',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Blanco', 'Azul', 'Rosa'],
  },
  {
    nombre: 'Camiseta Levi\'s',
    descripcion: 'Camiseta de algodón orgánico con logo de Levi\'s, estilo vintage.',
    precio: 27.99,
    stock: 40,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=500',
    marca: 'Levi\'s',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Blanco', 'Gris', 'Verde'],
  },
  {
    nombre: 'Camiseta Tommy Hilfiger',
    descripcion: 'Camiseta con logo bordado, algodón 100% y ajuste moderno.',
    precio: 44.99,
    stock: 20,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1554568218-0f1715e72254?w=500',
    marca: 'Tommy Hilfiger',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Blanco', 'Azul', 'Rojo'],
  },

  // ============================
  // PANTALONES (8)
  // ============================
  {
    nombre: 'Pantalón Deportivo Adidas',
    descripcion: 'Pantalón con tejido elástico, cintura ajustable y bolsillos laterales.',
    precio: 59.99,
    stock: 35,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1556906781-9a4129617d5b?w=500',
    marca: 'Adidas',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Gris', 'Azul'],
  },
  {
    nombre: 'Pantalón Cargo Nike',
    descripcion: 'Pantalón cargo con múltiples bolsillos y tela resistente.',
    precio: 69.99,
    stock: 25,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=500',
    marca: 'Nike',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Caqui', 'Negro', 'Oliva'],
  },
  {
    nombre: 'Pantalón Chino Zara',
    descripcion: 'Pantalón chino de algodón con corte recto y estilo formal-casual.',
    precio: 49.99,
    stock: 40,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500',
    marca: 'Zara',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Beige', 'Negro', 'Gris'],
  },
  {
    nombre: 'Pantalón Vaquero Levi\'s',
    descripcion: 'Jeans clásicos con corte recto y denim de alta calidad.',
    precio: 79.99,
    stock: 30,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500',
    marca: 'Levi\'s',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Azul', 'Negro', 'Gris'],
  },
  {
    nombre: 'Pantalón Jogger Puma',
    descripcion: 'Pantalón jogger con puños elásticos y tela suave, ideal para entrenar.',
    precio: 44.99,
    stock: 45,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1584865288642-42078afe6942?w=500',
    marca: 'Puma',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Gris', 'Azul'],
  },
  {
    nombre: 'Pantalón de Vestir H&M',
    descripcion: 'Pantalón de vestir con raya y tejido ligero, perfecto para oficina.',
    precio: 39.99,
    stock: 30,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=500',
    marca: 'H&M',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Gris', 'Azul'],
  },
  {
    nombre: 'Pantalón Corto New Balance',
    descripcion: 'Pantalón corto deportivo con forro interior y cintura elástica.',
    precio: 34.99,
    stock: 50,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1575079446555-6ae1b8a0b7ab?w=500',
    marca: 'New Balance',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Gris', 'Azul'],
  },
  {
    nombre: 'Pantalón Deportivo Under Armour',
    descripcion: 'Pantalón con tecnología UA Storm para repelencia al agua y transpiración.',
    precio: 64.99,
    stock: 20,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1584865288642-42078afe6942?w=500',
    marca: 'Under Armour',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Azul', 'Rojo'],
  },

  // ============================
  // CHAQUETAS (6)
  // ============================
  {
    nombre: 'Chaqueta Deportiva Nike',
    descripcion: 'Chaqueta cortavientos con capucha y forro interior de malla.',
    precio: 89.99,
    stock: 15,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
    marca: 'Nike',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Azul', 'Gris'],
  },
  {
    nombre: 'Chaqueta Adidas Originals',
    descripcion: 'Chaqueta clásica con rayas laterales y cuello alto.',
    precio: 79.99,
    stock: 18,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500',
    marca: 'Adidas',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Blanco', 'Rojo'],
  },
  {
    nombre: 'Chaqueta de Cuero Zara',
    descripcion: 'Chaqueta de cuero sintético con cierre frontal y bolsillos laterales.',
    precio: 119.99,
    stock: 10,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
    marca: 'Zara',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Marrón'],
  },
  {
    nombre: 'Chaqueta Plumas H&M',
    descripcion: 'Chaqueta acolchada con relleno de plumas y capucha desmontable.',
    precio: 99.99,
    stock: 12,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=500',
    marca: 'H&M',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Azul', 'Verde'],
  },
  {
    nombre: 'Chaqueta Denim Levi\'s',
    descripcion: 'Chaqueta vaquera clásica con botones metálicos y bolsillos frontales.',
    precio: 69.99,
    stock: 20,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1495105787522-5334e3ffa0ef?w=500',
    marca: 'Levi\'s',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Azul', 'Negro'],
  },
  {
    nombre: 'Chaqueta Puma Deportiva',
    descripcion: 'Chaqueta ligera con capucha ajustable y bolsillos con cremallera.',
    precio: 64.99,
    stock: 22,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500',
    marca: 'Puma',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Gris', 'Rojo'],
  },

  // ============================
  // VESTIDOS (4)
  // ============================
  {
    nombre: 'Vestido Floral Mango',
    descripcion: 'Vestido largo con estampado floral y tirantes ajustables.',
    precio: 69.99,
    stock: 18,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=500',
    marca: 'Mango',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Rojo', 'Amarillo', 'Blanco'],
  },
  {
    nombre: 'Vestido Casual Zara',
    descripcion: 'Vestido de corte recto con manga corta y tejido de punto.',
    precio: 49.99,
    stock: 25,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500',
    marca: 'Zara',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Azul', 'Beige'],
  },
  {
    nombre: 'Vestido Noche H&M',
    descripcion: 'Vestido de noche con escote y falda fluida, perfecto para eventos.',
    precio: 89.99,
    stock: 10,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=500',
    marca: 'H&M',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Rojo', 'Azul'],
  },
  {
    nombre: 'Vestido Verano Tommy Hilfiger',
    descripcion: 'Vestido de algodón con estampado marino y detalles de cordones.',
    precio: 79.99,
    stock: 15,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500',
    marca: 'Tommy Hilfiger',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Blanco', 'Azul', 'Rojo'],
  },

  // ============================
  // ZAPATILLAS (8) - AHORA CON TALLAS DE ROPA
  // ============================
  {
    nombre: 'Zapatillas Running Nike Air',
    descripcion: 'Zapatillas con amortiguación Air Max y suela de goma para running.',
    precio: 129.99,
    stock: 20,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    marca: 'Nike',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Rojo'],
  },
  {
    nombre: 'Zapatillas Adidas Ultraboost',
    descripcion: 'Zapatillas con tecnología Boost para máxima amortiguación y retorno de energía.',
    precio: 149.99,
    stock: 15,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    marca: 'Adidas',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Blanco', 'Gris'],
  },
  {
    nombre: 'Zapatillas Puma RS-X',
    descripcion: 'Zapatillas con diseño retro y amortiguación en el talón.',
    precio: 99.99,
    stock: 25,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    marca: 'Puma',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Azul'],
  },
  {
    nombre: 'Zapatillas New Balance 574',
    descripcion: 'Zapatillas clásicas con suela ENCAP y diseño atemporal.',
    precio: 89.99,
    stock: 30,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    marca: 'New Balance',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Gris', 'Azul', 'Rojo'],
  },
  {
    nombre: 'Zapatillas Under Armour HOVR',
    descripcion: 'Zapatillas con tecnología HOVR para amortiguación y respuesta.',
    precio: 119.99,
    stock: 18,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    marca: 'Under Armour',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Azul', 'Verde'],
  },
  {
    nombre: 'Zapatillas Converse Chuck Taylor',
    descripcion: 'Zapatillas de lona clásicas, estilo casual y versátil.',
    precio: 59.99,
    stock: 40,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1525966222134-4c4d32d8c617?w=500',
    marca: 'Converse',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Blanco', 'Rojo'],
  },
  {
    nombre: 'Zapatillas Vans Old Skool',
    descripcion: 'Zapatillas con diseño clásico y refuerzo en la puntera.',
    precio: 69.99,
    stock: 35,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1525966222134-4c4d32d8c617?w=500',
    marca: 'Vans',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Azul'],
  },
  {
    nombre: 'Zapatillas Reebok Classic',
    descripcion: 'Zapatillas de entrenamiento con diseño retro y suela de goma.',
    precio: 79.99,
    stock: 28,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    marca: 'Reebok',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Blanco', 'Gris'],
  },

  // ============================
  // GORRAS Y ACCESORIOS (4) - CON TALLAS DE ROPA
  // ============================
  {
    nombre: 'Gorra Deportiva Nike',
    descripcion: 'Gorra con visera curva, transpirable y ajustable con cierre de velcro.',
    precio: 19.99,
    stock: 60,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500',
    marca: 'Nike',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Azul'],
  },
  {
    nombre: 'Gorra Adidas Originals',
    descripcion: 'Gorra de algodón con logo bordado y ajuste trasero.',
    precio: 17.99,
    stock: 55,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500',
    marca: 'Adidas',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Rojo'],
  },
  {
    nombre: 'Gorra Puma',
    descripcion: 'Gorra deportiva con diseño aerodinámico y absorción de sudor.',
    precio: 15.99,
    stock: 45,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=500',
    marca: 'Puma',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Gris', 'Verde'],
  },
  {
    nombre: 'Bufanda de Lana Zara',
    descripcion: 'Bufanda de lana suave con diseño a cuadros, ideal para invierno.',
    precio: 29.99,
    stock: 25,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c7?w=500',
    marca: 'Zara',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Rojo', 'Negro', 'Gris'],
  },

  // ============================
  // ROPA INTERIOR Y MEDIAS (4)
  // ============================
  {
    nombre: 'Pack de Boxers Calvin Klein',
    descripcion: 'Pack de 3 boxers de algodón con elástico y logo CK.',
    precio: 39.99,
    stock: 30,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=500',
    marca: 'Calvin Klein',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Gris'],
  },
  {
    nombre: 'Pack de Calcetines Nike',
    descripcion: 'Pack de 6 pares de calcetines deportivos con refuerzo en talón.',
    precio: 24.99,
    stock: 50,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=500',
    marca: 'Nike',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Gris'],
  },
  {
    nombre: 'Braguitas H&M',
    descripcion: 'Set de 5 braguitas de algodón con diferentes colores.',
    precio: 19.99,
    stock: 40,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=500',
    marca: 'H&M',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Rosa', 'Azul'],
  },
  {
    nombre: 'Medias Deportivas Adidas',
    descripcion: 'Medias con compresión y soporte para el arco, ideales para running.',
    precio: 14.99,
    stock: 35,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=500',
    marca: 'Adidas',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Blanco', 'Rojo'],
  },

  // ============================
  // SUDADERAS (4)
  // ============================
  {
    nombre: 'Sudadera Nike Club',
    descripcion: 'Sudadera de algodón con capucha y bolsillo canguro.',
    precio: 54.99,
    stock: 22,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
    marca: 'Nike',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Gris', 'Azul'],
  },
  {
    nombre: 'Sudadera Adidas Originals',
    descripcion: 'Sudadera con logo y rayas laterales, tejido felpa suave.',
    precio: 59.99,
    stock: 20,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
    marca: 'Adidas',
    tallas: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colores: ['Negro', 'Blanco', 'Rojo'],
  },
  {
    nombre: 'Sudadera Puma Essentials',
    descripcion: 'Sudadera básica con cuello redondo y ribetes en puños.',
    precio: 44.99,
    stock: 25,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
    marca: 'Puma',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Negro', 'Gris', 'Verde'],
  },
  {
    nombre: 'Sudadera Zara Básica',
    descripcion: 'Sudadera de algodón con cuello redondo y ajuste regular.',
    precio: 39.99,
    stock: 30,
    categoria: 'ropa',
    imagen: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=500',
    marca: 'Zara',
    tallas: ['XS', 'S', 'M', 'L', 'XL'],
    colores: ['Beige', 'Negro', 'Azul'],
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Conectado a MongoDB');

    await Product.deleteMany();
    console.log('🗑️ Productos eliminados');

    await Product.insertMany(products);
    console.log(`✅ ${products.length} productos de ropa insertados correctamente`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error al insertar productos:', error);
    process.exit(1);
  }
};

seedDB();